# https://golangci-lint.run/usage/configuration/
run:
  skip-files:
    - ".*_mock\\.go"
  tests: false
  deadline: 5m
  print-resources-usage: true

linters:
  enable-all: true
  disable:
    - gci              # Gci control golang package import order and make it always deterministic.
    - gochecknoglobals # Checks that no globals are present in Go code [fast: true, auto-fix: false]
    - gofumpt          # Gofumpt checks whether code was gofumpt-ed.
    - gomnd            # An analyzer to detect magic numbers. [fast: true, auto-fix: false]
    - gosec            # Inspects source code for security problems.
    - ireturn          # Accept Interfaces, Return Concrete Types
    - varnamelen       # Check the input of parameter has the short length or not.
    - wrapcheck        # Checks that errors returned from external packages are wrapped.

linters-settings:
  govet:
    # https://github.com/golangci/golangci-lint/issues/484
    # report about shadowed variables
    check-shadowing: false
  lll:
    line-length: 150
